# 1). Import libraries

In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import ipywidgets as widgets
from ipywidgets import interact

from imblearn.over_sampling import RandomOverSampler
from imblearn.under_sampling import RandomUnderSampler
from sklearn.model_selection import train_test_split, GridSearchCV, cross_val_score
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.metrics import ConfusionMatrixDisplay, classification_report, confusion_matrix

# 2). Load Data

In [3]:
df=pd.read_csv("/workspaces/Predicting_Companies-_Bankruptcy_in_Taiwan-Ensemble-Modelling-/data/taiwanese+bankruptcy+prediction.zip")
df.head(3)

   Bankrupt?  ...   Equity to Liability
0          1  ...              0.016469
1          1  ...              0.020794
2          1  ...              0.016474

[3 rows x 96 columns]

# 3). Split

In [6]:
# Feature-target split
target="Bankrupt?"
X=df.drop(columns=target)
y=df[target]
print("X", X.shape)
print("y", y.shape)

X (6819, 95)
y (6819,)

In [9]:
# Randomized train test split
X_train, X_test, y_train, y_test=train_test_split(X, y, test_size=0.2, random_state=42)
print("X_train", X_train.shape)
print("y_train", y_train.shape)
print("X_test", X_test.shape)
print("y_test", y_test.shape)

X_train (5455, 95)
y_train (5455,)
X_test (1364, 95)
y_test (1364,)

# 4) Resample

In [10]:
under_sampler=RandomUnderSampler(random_state=42)
X_train_under, y_train_under=under_sampler.fit_resample(X_train, y_train)
print("X_train_under", X_train_under.shape)
print("y_train_under", y_train_under.shape)
over_sampler=RandomOverSampler(random_state=42)
X_train_over, y_train_over=over_sampler.fit_resample(X_train, y_train)
print("X_train_over", X_train_over.shape)
print("X_train_over", X_train_over.shape)

X_train_under (338, 95)
y_train_under (338,)
X_train_over (10572, 95)
X_train_over (10572, 95)

# 5). Build Models

## Baselining

In [12]:
baseline_acc=df["Bankrupt?"].value_counts(normalize=True).max()
print("Baseline accuracy:",baseline_acc)

Baseline accuracy: 0.967737204868749

## a) Random Forest

In [13]:
# Instantiate classifier
clf1=RandomForestClassifier(random_state=42)
# Cross validation
cv_acc_scores=cross_val_score(clf1, X_train, y_train, cv=5, n_jobs=-1)
print(cv_acc_scores)

[0.96975252 0.9715857  0.97433547 0.97341888 0.97250229]

In [17]:
# Grid Search
params = {
    "n_estimators": range(25, 100, 25),
    "max_depth": range(10, 50, 10)
}
params

{'n_estimators': range(25, 100, 25), 'max_depth': range(10, 50, 10)}

In [18]:
# Instantiate and fit for all sets
model_under=GridSearchCV(
    clf1,
    param_grid=params,
    cv=5,
    n_jobs=-1,
    verbose=1
)
model_under.fit(X_train_under, y_train_under)

Fitting 5 folds for each of 12 candidates, totalling 60 fits

GridSearchCV(cv=5, estimator=RandomForestClassifier(random_state=42), n_jobs=-1,
             param_grid={'max_depth': range(10, 50, 10),
                         'n_estimators': range(25, 100, 25)},
             verbose=1)

In [19]:
model_train=GridSearchCV(
    clf1,
    param_grid=params,
    cv=5,
    n_jobs=-1,
    verbose=1
)
model_train.fit(X_train, y_train)

Fitting 5 folds for each of 12 candidates, totalling 60 fits

GridSearchCV(cv=5, estimator=RandomForestClassifier(random_state=42), n_jobs=-1,
             param_grid={'max_depth': range(10, 50, 10),
                         'n_estimators': range(25, 100, 25)},
             verbose=1)

In [20]:
model_over=GridSearchCV(
    clf1,
    param_grid=params,
    cv=5,
    n_jobs=-1,
    verbose=1
)
model_over.fit(X_train_over, y_train_over)

Fitting 5 folds for each of 12 candidates, totalling 60 fits

GridSearchCV(cv=5, estimator=RandomForestClassifier(random_state=42), n_jobs=-1,
             param_grid={'max_depth': range(10, 50, 10),
                         'n_estimators': range(25, 100, 25)},
             verbose=1)

In [21]:
# Extract best params from all models
print("Model_under best params:", model_under.best_params_)
print("Model_train best params:", model_train.best_params_)
print("Model_over best params:", model_over.best_params_)

Model_under best params: {'max_depth': 10, 'n_estimators': 50}
Model_train best params: {'max_depth': 20, 'n_estimators': 75}
Model_over best params: {'max_depth': 40, 'n_estimators': 50}

In [23]:
# Extract results
results_under=pd.DataFrame(model_under.cv_results_)
results_over=pd.DataFrame(model_over.cv_results_)
results_train=pd.DataFrame(model_train.cv_results_)

In [31]:
results_under.sort_values(by="mean_test_score", ascending=False).head()

    mean_fit_time  std_fit_time  ...  std_test_score  rank_test_score
1        0.184309      0.072066  ...        0.017117                1
2        0.335826      0.068651  ...        0.010954                1
5        0.189617      0.013819  ...        0.010954                1
4        0.131888      0.014738  ...        0.017117                1
11       0.181788      0.001932  ...        0.010954                1

[5 rows x 15 columns]

In [32]:
results_train.sort_values(by="mean_test_score", ascending=False).head()

    mean_fit_time  std_fit_time  ...  std_test_score  rank_test_score
8        2.260812      0.107551  ...        0.001700                1
11       2.070875      0.138518  ...        0.001700                1
5        2.139431      0.085784  ...        0.001700                1
4        1.464137      0.032789  ...        0.001216                4
10       1.488736      0.095018  ...        0.001216                4

[5 rows x 15 columns]

In [33]:
results_over.sort_values(by="mean_test_score", ascending=False).head()

    mean_fit_time  std_fit_time  ...  std_test_score  rank_test_score
10       2.123586      0.135280  ...        0.001357                1
11       3.069641      0.149278  ...        0.000964                2
9        1.073426      0.055975  ...        0.000627                3
8        3.087125      0.152574  ...        0.000641                4
7        2.067673      0.018729  ...        0.000707                5

[5 rows x 15 columns]

### Evaluate

In [40]:
print("Under sampled accuracy:", round(model_under.score(X_test, y_test),2))
print("Train accuracy:", round(model_train.score(X_test, y_test), 2))
print("Over sampled accuracy:", round(model_over.score(X_test, y_test), 2))

Under sampled accuracy: 0.86
Train accuracy: 0.97
Over sampled accuracy: 0.97

From the accuracy scores from the CV results, it is clear that the model train